name: DS Api client
on: 
  workflow_dispatch
  
jobs:
  tests:
    name: Run unit tests 
    if: ${{ github.base_ref == 'develop' || github.base_ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: run test unit
        env: 
          API_URL: ${{secrets.API_URL}}
          API_TOKEN: ${{secrets.API_TOKEN}}
        run: | 
            npm ci
            npm run lint
            API_URL=${{secrets.API_URL}}; API_TOKEN=${{secrets.API_TOKEN}}; npm run test             
      - name: run build
        run: npm run build
      - name: deploy
        run: npm version patch
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: update branch        
        uses: EndBug/add-and-commit@v9
           add: 'package*.json'
           message: 'update version'
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
